#[test]
fn fail() {
    panic!("a")
}